### ISSUE TITLE
Bug with Firebase

### ISSUE THREAD

**Issue by marc-farre** [ONLYOFFICE/onlyoffice-humhub#106]
Log:

```
ArgumentCountError: Too few arguments to function Firebase\JWT\JWT::encode(), 2 passed in /var/www/humhub/protected/modules/onlyoffice/Module.php on line 399 and at least 3 expected in /var/www/humhub/protected/vendor/firebase/php-jwt/src/JWT.php:193
Stack trace:
#0 /var/www/humhub/protected/modules/onlyoffice/Module.php(399): Firebase\JWT\JWT::encode()
#1 /var/www/humhub/protected/modules/onlyoffice/widgets/EditorWidget.php(157): humhub\modules\onlyoffice\Module->generateHash()
#2 /var/www/humhub/protected/modules/onlyoffice/widgets/EditorWidget.php(116): humhub\modules\onlyoffice\widgets\EditorWidget->getConfig()
#3 /var/www/humhub/protected/humhub/widgets/JsWidget.php(98): humhub\modules\onlyoffice\widgets\EditorWidget->getData()
#4 /var/www/humhub/protected/modules/onlyoffice/widgets/EditorWidget.php(144): humhub\widgets\JsWidget->getOptions()
#5 /var/www/humhub/protected/humhub/components/Widget.php(63): humhub\modules\onlyoffice\widgets\EditorWidget->run()
#6 /var/www/humhub/protected/modules/onlyoffice/views/open/index.php(15): humhub\components\Widget::widget()
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require('/usr/www/users/...')
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#9 /var/www/humhub/protected/humhub/modules/ui/view/components/View.php(240): yii\base\View->renderFile()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Controller.php(50): humhub\modules\ui\view\components\View->renderAjax()
#11 /var/www/humhub/protected/modules/onlyoffice/controllers/OpenController.php(58): yii\web\Controller->renderAjax()
#12 [internal function]: humhub\modules\onlyoffice\controllers\OpenController->actionIndex()
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#14 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#18 /var/www/humhub/index.php(25): yii\base\Application->run()
#19 {main}
```

**Comment by luke-** [comment]
There is already a merged fix for this: https://github.com/ONLYOFFICE/onlyoffice-humhub/pull/99

We plan to release the stable HumHub v1.15 version soon. So a soon Onlyoffice module release would be important.
