### ISSUE TITLE
Humhub based documents do not work as expected. OpenOffice integration not usable.

### ISSUE THREAD

**Issue by optitsolutions** [ONLYOFFICE/onlyoffice-humhub#107]
If I want to edit a docx file via OO, it opens a sample file with content about humhub languages etc. In the header appears the correct file name. If I change content and save the file, the changed version is stored in cfiles module (new version entry -alright), but I cannot open or edit the changed document via OO module. It shows the same sample content at each time.

If I want to open a not docx-file (e.g. pptx, xlsx). OO shows an error message regarding file extensions that do not match. OO probably wants to open the sample page here too.

OnlyOffice Connector is working. All modules and Humhub are up to date.

With this error the OO integration in humhub is not usable.

**Comment by SergeyKorneyev** [comment]
Hello,

Could you check if the value of the "Authorization header" field in the connector's settings matches the one of the `services.CoAuthoring.token.inbox.header` parameter in Document Server's **local.json**? The local.json config file can be found in /etc/onlyoffice/documentserver/ for Linux installations and in %ProgramFiles%\ONLYOFFICE\Document Server\config\ on Windows.

**Comment by WizWareTech** [comment]
I am having this same problem. I checked and headers are identical. I also tried setting them both to default 'Authorization' and it still has the same issue.  (see https://github.com/ONLYOFFICE/onlyoffice-humhub/issues/103)

**Comment by dreua** [comment]
Are this case where it worked before and stopped at some point or did it never work?
Usually some details about the setup are helpful to asses the situation, like versions used, Maybe OS and which kind of document server you are using.

**Comment by optitsolutions** [comment]
We can do tests with the Header tomorrow. I'll give a feedback here.

**Comment by optitsolutions** [comment]
With HH 1.14 it doesn't work. And it doesn't work with the mentioned edits in https://github.com/humhub/humhub/issues/6497 and
https://github.com/humhub/humhub/issues/6535
It would be nice to get any solutions.
We tested with different authorization headers, without authorization headers, with hash function and without.

**Comment by WizWareTech** [comment]
Can anyone help with this? It has been broken for months now and is such a critical thing.

**Comment by WizWareTech** [comment]
Can anyone help with this? It's been months that this hasn't worked now. I was able to find some more info in OO log:

[2023-11-10T13:32:33.103] [ERROR] [localhost] [b735e0a521c83fbe2c07] [d476e189-fa9b-4d23-8f7e-08b109133810] nodeJS - postData error: url = https://forum.private.org/onlyoffice/backend/track?doc=eyJ0eXAiOiJKV1QJhbGciOiJIUzI1NiJ9.eyJrZXkiOiJiNzM1ZTBhNTIxYzgzZmJlMmMwNyIsInVzZXJHdWlkIjoiZDQ3NmUxODktZmE5Yi00ZDIzLThmN2UtMDhiMTA5MTMzODEwIn0.8CzZJZE5JDDFsu0SWQ_jxg4ur4KgwTcqLf4J_9pBLfA;data = {"key":"b735e0jj21c83fbe2c07","status":1,"users":["d476ej89-fa9b-4d23-8f7e-08b109133810"],"actions":[{"type":1,"userid":"d476e189-fa9b-4d23-8f7e-08b109133810"}],"token":"eyJhbGciOiJIUzI1NiIsInRI6IkpXVCJ9.eyJrZXkiOiJiNzM1ZTBhNTIxYzgzZmJlMmMwNyIsInN0YXR1cyI6MSwidXNlcnMiOlsiZDQ3NmUxODktZmE5Yi00ZDIzLThmN2UtMDhiMTA5MTMzODEwIl0sImFjdGlvbnMiOlt7InR5cGUiOjEsInVzZXJpZCI6ImQ0NzZlMTg5LWZhOWItNGQyMy04ZjdlLTA4YjEwOTEzMzgxMCJ9XSwiaWF0IjoxNjk5NjQ4MzUzLCJleHAiOjE2OTk2NDg2NTN9.eckCUiTn8k8pal0VBbBFzyg9INk_H_c_ZnEF7S-_ZvA"} Error: Error response: statusCode:302; headers:{"date":"Fri, 10 Nov 2023 20:32:33 GMT","content-encoding":"gzip","transfer-encoding":"chunked","content-type":"text/html; charset=UTF-8","server":"openresty","location":"http://forum.private.org/user/auth/login","x-served-by":"forum.private.org","x-hw":"1699648353.cds212.de1.hc,1699648353.cds226.de1.sc,1699648353.cds226.de1.p","access-control-allow-origin":"*","connection":"close"}; body:

    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:400:28)
    at Gunzip.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:519:28)
    at Gunzip.emit (events.js:400:28)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
